from __future__ import annotations

import logging

from langchain_core.messages import HumanMessage, SystemMessage

from codesentinel.agents.state import ReviewState
from codesentinel.config import get_llm

logger = logging.getLogger(__name__)

SUMMARY_SYSTEM = """You are a senior tech lead writing a structured code review for a GitHub pull request.
Synthesize the security and quality findings into a clear, actionable review comment.

Format your review as GitHub-flavored Markdown with these sections:

## CodeSentinel Review

### Summary
[1-2 sentence overall assessment]

### Security Findings
[List critical/high findings first; include file:line references]

### Code Quality
[Key quality issues with suggestions]

### Positive Observations
[What was done well — always include at least one]

### Recommendation
**[APPROVE / REQUEST_CHANGES / COMMENT]** — [one sentence rationale]

---
*🤖 Generated by [CodeSentinel](https://github.com) — AI-powered PR review*

Be direct, constructive, and specific. Prioritize critical/high severity findings."""


def summary_agent_node(state: ReviewState) -> dict:
    """Merge security + quality findings into a final Markdown review comment."""
    logger.info("summary_agent: generating final review for %s PR #%d", state["repo"], state["pr_number"])

    security_findings = state.get("security_findings", [])
    quality_findings = state.get("quality_findings", [])

    # Format findings for LLM context
    sec_parts = []
    for f in security_findings:
        if f.get("severity") != "info" or f.get("id", "").startswith("OWASP"):
            location = f"({f.get('file', 'unknown')}:{f.get('line', '?')})" if f.get("file") else ""
            sec_parts.append(
                f"- [{f.get('severity', 'info').upper()}] {f.get('id', 'Finding')}: "
                f"{f.get('description', '')} {location}"
            )

    # Include LLM security analysis narratives
    for f in security_findings:
        if f.get("id") == "LLM-SECURITY-ANALYSIS":
            sec_parts.append(f"\nSecurity analysis:\n{f.get('description', '')}")

    qual_parts = []
    for f in quality_findings:
        if f.get("id") == "LLM-QUALITY-ANALYSIS":
            qual_parts.append(f.get("description", ""))
        else:
            location = f"({f.get('file', 'unknown')}:{f.get('line', '?')})" if f.get("file") else ""
            qual_parts.append(
                f"- [{f.get('severity', 'info').upper()}] {f.get('description', '')} {location}"
            )

    critical_count = sum(1 for f in security_findings if f.get("severity") == "critical")
    high_count = sum(1 for f in security_findings + quality_findings if f.get("severity") == "high")

    llm = get_llm()
    response = llm.invoke([
        SystemMessage(content=SUMMARY_SYSTEM),
        HumanMessage(
            content=(
                f"Repository: {state['repo']}\n"
                f"PR #{state['pr_number']}: {state.get('pr_url', '')}\n"
                f"Files reviewed: {', '.join(state.get('changed_files', []))}\n"
                f"Critical findings: {critical_count}, High findings: {high_count}\n\n"
                f"SECURITY FINDINGS:\n"
                + ("\n".join(sec_parts) if sec_parts else "No security issues detected.")
                + f"\n\nQUALITY FINDINGS:\n"
                + ("\n".join(qual_parts) if qual_parts else "No quality issues detected.")
                + "\n\nPlease generate the final review comment."
            )
        ),
    ])

    final_review = response.content if hasattr(response, "content") else str(response)
    logger.info("summary_agent: review generated (%d chars)", len(final_review))

    return {"final_review": final_review}
