from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class InvestmentReport(BaseModel):
    """Structured investment brief produced by the report_writer agent."""

    ticker: str = Field(description="Stock ticker symbol")
    company_name: str = Field(description="Full company name")
    recommendation: str = Field(
        description="Investment recommendation: BUY | HOLD | SELL | SPECULATIVE_BUY"
    )
    confidence_score: int = Field(
        description="Confidence in the recommendation, 0-100", ge=0, le=100
    )
    target_price_12m: Optional[float] = Field(
        default=None, description="12-month price target in USD"
    )
    current_price: Optional[float] = Field(default=None, description="Current stock price in USD")
    upside_downside_pct: Optional[float] = Field(
        default=None, description="Expected upside (positive) or downside (negative) percentage"
    )

    # Research sections
    executive_summary: str = Field(description="2-3 sentence executive summary")
    investment_thesis: str = Field(description="Core investment thesis (3-5 bullet points as text)")
    financial_highlights: str = Field(description="Key financial metrics and trends")
    risks: str = Field(description="Key risks and mitigation factors")
    sentiment_summary: str = Field(description="Market and analyst sentiment overview")

    # Metadata
    data_sources: list[str] = Field(
        default_factory=list, description="Data sources used in the analysis"
    )
    disclaimer: str = Field(
        default=(
            "This report is generated by an AI system for informational purposes only. "
            "It does not constitute financial advice. Always consult a qualified financial advisor "
            "before making investment decisions."
        )
    )


class ResearchResponse(BaseModel):
    thread_id: str
    status: str  # "started" | "running" | "awaiting_approval" | "completed" | "failed"
    ticker: Optional[str] = None
    message: Optional[str] = None


class StatusResponse(BaseModel):
    thread_id: str
    status: str
    ticker: Optional[str] = None
    current_step: Optional[str] = None
